version: '3'

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'tutoring_api_2022'
      MYSQL_DATABASE: tutoring_database
    ports:
      - 3306:3306
  elasticmq:
    image: softwaremill/elasticmq-native
    ports:
      - 9324:9324
      - 9325:9325